In [1]:
import numpy as np
import pandas as pd

In [7]:
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [8]:
# more than one dimensions 

a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


In [10]:
# minimum dimensions 

a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [12]:
#Create an array with data type string:

a = np.array([1, 2, 3], dtype ='S') 
print(a)

[b'1' b'2' b'3']


In [13]:
print("a ndim: ", a.ndim)
print("a shape:", a.shape)
print("a size: ", a.size)

a ndim:  1
a shape: (3,)
a size:  3


In [14]:
print("itemsize:", a.itemsize, "bytes")
print("nbytes:", a.nbytes, "bytes")

itemsize: 1 bytes
nbytes: 3 bytes


In [19]:
a[0], a[1]

(b'1', b'2')

In [20]:
a[-1]

b'3'

In [22]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

In [23]:
a[0, 0]

30

In [ ]:
# chnging the value by efining their index 

a[0,0] = 12

In [25]:
# creating copies of array

a_copy = a[:2, :2].copy()
print(a_copy)

[[30 40]
 [80 20]]


In [2]:
city = ['Karachi','Lahore','Islamabad12']
weight = [65.5,70.5,80]
fastfoodsales=[4000,8000,7000]

In [27]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# concatenate two arrays


x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [29]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [30]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [32]:
# splitting arrays

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [33]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a = np.array([1,2,3]) 
print(a)

In [ ]:
# more than one dimensions 

a = np.array([[1, 2], [3, 4]]) 
print(a)

In [ ]:
print("a ndim: ", a.ndim)
print("a shape:", a.shape)
print("a size: ", a.size)

In [ ]:
print("itemsize:", a.itemsize, "bytes")
print("nbytes:", a.nbytes, "bytes")

In [ ]:
a[0], a[1]
a[-1]

In [ ]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
a[0, 0]

In [ ]:
# chnging the value by efining their index 

a[0,0] = 12

In [ ]:
# creating copies of array

a_copy = a[:2, :2].copy()
print(a_copy)

In [34]:
city = ['Karachi','Lahore','Islamabad12']
weight = [65.5,70.5,80]
fastfoodsales=[4000,8000,7000]

In [35]:
type(weight)

list

In [36]:
fastfoodsales/weight

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
sales_per_weight=np.divide(fastfoodsales,weight)


In [8]:
type(sales_per_weight)

numpy.ndarray

In [9]:
#weight*2
#weight_array*2
#When to use np.multiply() and when to use array_object*2?

In [1]:
#print(salesperkg)

In [11]:
city_array=np.array(city)
weight_array=np.array(weight)
ffsales_array=np.array(fastfoodsales)


In [12]:
print(city_array)

['Karachi' 'Lahore' 'Islamabad12']


In [13]:
type(city_array)

numpy.ndarray

In [14]:
ff_visits_per_month=np.array([5,6],dtype='object')

In [15]:
ff_visits_per_month*2

array([10, 12], dtype=object)

In [16]:
ff_visits_per_month_int=ff_visits_per_month.astype(int)

In [17]:
ff_visits_per_month_int.dtype

dtype('int32')

In [18]:
print(ff_visits_per_month)

[5 6]


In [19]:
print(ff_visits_per_month.dtype)

object


In [20]:
print(type(ff_visits_per_month),type(weight),type(weight_array))


<class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [21]:
print(weight_array.dtype)

float64


In [22]:
print(type(city_array),type(weight_array),type(ffsales_array),type(ff_visits_per_month))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [23]:
print(city_array.dtype,weight_array.dtype,ffsales_array.dtype)

<U11 float64 int32


In [24]:
print(weight_array)

[65.5 70.5 80. ]


In [25]:
consolidated = zip(city_array,weight_array,ffsales_array)

In [26]:
print(consolidated)

In [27]:
consolidated_array=np.array(list(consolidated))

In [28]:
city = ['Karachi','Lahore','Islamabad']
weight = [65.5,70.5,80]
fastfoodsales=[4000,8000,7000]

In [29]:
print(consolidated_array)

[['Karachi' '65.5' '4000']
 ['Lahore' '70.5' '8000']
 ['Islamabad12' '80.0' '7000']]


In [30]:
print(consolidated_array.dtype,weight_array.dtype,city_array.dtype)

<U11 float64 <U11


In [31]:
consolidated_array*2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [32]:
corarray=np.corrcoef(weight_array,ffsales_array)

In [33]:
print(type(corarray),corarray)

<class 'numpy.ndarray'> [[1.        0.5869912]
 [0.5869912 1.       ]]


In [34]:
corarray[1,0]

0.5869911985194601

In [35]:
np.ndim(corarray)

2

In [36]:
ravarray=np.ravel(corarray)

In [37]:
ravarray

array([1.       , 0.5869912, 0.5869912, 1.       ])

In [38]:
np.ndim(ravarray)

1

In [39]:
ravarray.reshape(2,2)

array([[1.       , 0.5869912],
       [0.5869912, 1.       ]])

In [40]:
np.shape(ravarray)

(4,)

In [41]:
corarray[0,1]

0.5869911985194601

In [42]:
np.mean(weight)

72.0

In [43]:
type(consolidated)

zip

In [44]:
consolidated.dtype

AttributeError: 'zip' object has no attribute 'dtype'

In [45]:
div_array=ffsales_array/weight_array

In [46]:
np.divide(fastfoodsales,weight)

array([ 61.06870229, 113.4751773 ,  87.5       ])

In [47]:
print(div_array)

[ 61.06870229 113.4751773   87.5       ]


In [48]:
add_array=np.negative(ffsales_array,weight_array)

In [49]:
print(add_array)

[-4000. -8000. -7000.]


In [50]:
mix = np.array([90,-50,100])

In [51]:
mixabs=np.absolute(mix)

In [52]:
print(mixabs)

[ 90  50 100]


In [53]:
a= np.arange(5,10,2)

In [54]:
a

array([5, 7, 9])

In [56]:
type(a)

numpy.ndarray

In [57]:
a.dtype

dtype('int32')

In [39]:
c=np.arange(12)

In [40]:
print(c)
print(type(c))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [41]:
d=c.reshape(3,2,2)

In [42]:
print(d)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [64]:
np.ndim(d)

3

In [43]:
a.shape


(3, 3)

In [44]:
d.shape

(3, 2, 2)

In [45]:
d.shape

(3, 2, 2)

In [46]:
c.dtype

dtype('int32')

In [47]:
# discuss ravel and unravel
d.ravel

<function ndarray.ravel>

In [48]:
e=d.ravel()

In [49]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
# NP.EMPTY, NP.ONES, NP.ZEROS, ZEROSLIKE, ONESLIKE

np.ones(3)

array([1., 1., 1.])

In [76]:
g=np.array([1,2,3,4,5])

In [77]:
h=np.array([4,5,6,7,8])

In [78]:
np.multiply(g,h)

array([ 4, 10, 18, 28, 40])

In [79]:
np.floor(h)

array([4., 5., 6., 7., 8.])

In [80]:
weight_array[weight_array>66]

array([], dtype=float64)

In [81]:
weight_array>66

array([False, False, False])

In [82]:
print(consolidated_array)

[['Karachi' '65.5' '4000']
 ['Lahore' '70.5' '8000']
 ['Islamabad12' '80.0' '7000']]


In [83]:
print(consolidated_array[1])

['Lahore' '70.5' '8000']


In [84]:
print(consolidated_array[1,0])

Lahore


In [85]:
print(consolidated_array[0,0:2])

['Karachi' '65.5']


In [86]:
print(consolidated_array[0:2,0:2])

[['Karachi' '65.5']
 ['Lahore' '70.5']]
